starting throwable pattern test
plain pattern, no exception
plain pattern, with exception
java.lang.Exception: Test Exception
	at org.apache.log4j.EnhancedPatternLayoutTestCase.testThrowable(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
%throwable, no exception
%throwable, with exception
java.lang.Exception: Test Exception
	at org.apache.log4j.EnhancedPatternLayoutTestCase.testThrowable(X)
	at java.lang.reflect.Method.invoke(X)
	at junit.framework.TestCase.runTest(X)
	at junit.framework.TestCase.runBare(X)
	at junit.framework.TestResult$1.protect(X)
	at junit.framework.TestResult.runProtected(X)
	at junit.framework.TestResult.run(X)
	at junit.framework.TestCase.run(X)
	at junit.framework.TestSuite.runTest(X)
	at junit.framework.TestSuite.run(X)
%throwable{short}, no exception
%throwable{short}, with exception
java.lang.Exception: Test Exception
%throwable{none}, no exception
%throwable{none}, with exception
